<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'tubalmartin\\CssMin\\' => array($vendorDir . '/tubalmartin/cssmin/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'ProseMirrorToHtml\\' => array($vendorDir . '/ueberdosis/prosemirror-to-html/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Intervention\\HttpAuth\\' => array($vendorDir . '/intervention/httpauth/src'),
    'HtmlToProseMirror\\' => array($vendorDir . '/ueberdosis/html-to-prosemirror/src'),
);
